# Generated by Django 4.1.4 on 2022-12-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, default=1976, null=True, verbose_name='date'),
        ),
    ]
