# Generated by Django 4.1.4 on 2022-12-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, default='2000-02-22', null=True, verbose_name='date'),
        ),
    ]
